# -*- coding: utf-8 -*-
"""프로그램2-1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18xqj4pso_LtWaXhn90R4gZp2gcUpBBbe
"""

print(12+37)
print('python' + ' is exciting.')

import random

a = random.randint(10,20)
b = random.randint(10,20)

c = a+b
print(a,b,c)